# GitHub Action Secrets:
# UNITY_LICENSE: Unity license file content
# UNITY_EMAIL: Unity account email
# UNITY_PASSWORD: Unity account password
# STEAM_USERNAME: Steam account username
# STEAM_CONFIG_VDF: Steam config file content
# ITCH_IO_API_KEY: Itch.io API Key (Required for Itch deployment)

# Github Action Variables:
# UNITY_VERSION: Unity version (e.g. 2023.2.9f1)
# STEAM_APP_ID: Steam app ID (e.g. 123456)
# BUILD_PLATFORMS: JSON array of platforms (e.g. ["StandaloneWindows64", "StandaloneLinux64", "StandaloneOSX", "WebGL"])
# ITCH_URL: Itch game slug (e.g. "my-awesome-game")
# ITCH_USER_NAME: Itch username (e.g. "my-username")
# ITCH_BUTLER_URL: https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default

name: CI/CD
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Build on multiple platforms 
  build-multiple-platforms:
    name: Build Multiple Platforms
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' 
    strategy:
      matrix: 
        targetPlatform: ${{ fromJSON(vars.BUILD_PLATFORMS) }}
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v4
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
          
      - name: Build project 
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ vars.UNITY_VERSION }}
          allowDirtyBuild: true

      # Output
      - name: Upload the file to Github Action
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}  
          path: build/${{ matrix.targetPlatform }}  
        
  # Deploy to Steam and itch
  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [build-multiple-platforms]
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Download all builds
        uses: actions/download-artifact@v4
        with:
          path: build
        
      - name: Auto-detect Steam Builds
        id: steam_detect
        run: |
          if [ -d "build/StandaloneWindows64" ]; then echo "win=StandaloneWindows64" >> $GITHUB_ENV; fi
          if [ -d "build/StandaloneLinux64" ]; then echo "linux=StandaloneLinux64" >> $GITHUB_ENV; fi
          if [ -d "build/StandaloneOSX" ]; then echo "mac=StandaloneOSX" >> $GITHUB_ENV; fi

      - name: Deploy to Steam
        if: ${{ vars.STEAM_APP_ID != '' }}
        uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          appId: ${{ vars.STEAM_APP_ID }}
          buildDescription: ${{ github.event.head_commit.message }}
          rootPath: build
          # By using env variables, if a platform isn't built, it passes an empty string
          depot1Path: ${{ env.win }}
          depot2Path: ${{ env.linux }}
          depot3Path: ${{ env.mac }}

      - name: Deploy to Itch
        if: ${{ vars.ITCH_URL != '' }}
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }} 
        run: |
          curl -L -o butler.zip ${{vars.ITCH_BUTLER_URL}}
          unzip butler.zip
          chmod +x butler
          
          # Loop through every folder inside 'build/'
          for folder in build/*; do
            if [ -d "$folder" ]; then
              platform=$(basename "$folder")
              channel=""
            
              if [ "$platform" == "StandaloneWindows64" ]; then channel="windows"; fi
              if [ "$platform" == "StandaloneOSX" ]; then channel="mac"; fi
              if [ "$platform" == "StandaloneLinux64" ]; then channel="linux"; fi
              if [ "$platform" == "WebGL" ]; then channel="web"; fi
              
              # If a valid channel is found, push it
              if [ "$channel" != "" ]; then
                echo "Uploading $platform to Itch channel: $channel..."
                ./butler push "$folder" "${{ vars.ITCH_USER_NAME }}/${{ vars.ITCH_URL }}:$channel"
              fi
            fi
          done
